apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  chart:
    spec:
      chart: ./charts/home-assistant
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: atlas-repo
        namespace: flux-system
  interval: 5m
  values:
    persistence:
      hostPath: /srv/data/home-assistant
    ingress:
      enabled: true
      hosts:
        - host: ha.atlas.lan
          paths: ["/"]
      ingressClassName: traefik