apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nodered
  namespace: default
spec:
  chart:
    # path to chart inside your git repo
    spec:
      chart: ./charts/nodered
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: atlas-repo
        namespace: flux-system
  interval: 5m
  values:
    persistence:
      hostPath: /srv/data/nodered
    ingress:
      enabled: true
      hosts:
        - host: nodered.atlas.lan
          paths: ["/"]
      ingressClassName: nginx