apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/uptimekuma
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: atlas-repo
        namespace: flux-system
  interval: 5m
  values:
    persistence:
      hostPath: /srv/data/uptime-kuma
    ingress:
      enabled: true
      hosts:
        - host: uptime.atlas.lan
          paths: ["/"]
      ingressClassName: nginx