apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: apps
spec:
  releaseName: zitadel
  interval: 10m

  chart:
    spec:
      chart: zitadel
      version: "9.2.0"
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: flux-system

  values:
    # -------------------------
    # Core Zitadel settings
    # -------------------------
    zitadel:
      masterkey: "3cPOX4bvn8kyiVnpsSZcJXJyQLgEUVTn4Qw6t09n3vk="

      configmapConfig:
        ExternalDomain: zitadel.atlas.lan
        ExternalSecure: true

        FirstInstance:
          Skip: false
          Org:
            Machine:
              Machine:
                Name: "IAM Admin"
                Username: "iam-admin"
              Pat:
                ExpirationDate: "2029-01-01T00:00:00Z"

    # -------------------------
    # Embedded CockroachDB
    # -------------------------
    cockroachdb:
      enabled: true
      singleNode: true

      persistence:
        enabled: true
        storageClass: local-path
        size: 5Gi

    # -------------------------
    # Ingress
    # -------------------------
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: zitadel.atlas.lan
          paths:
            - path: /
              pathType: Prefix
